### ISSUE TITLE
Bukkit-API mode: Missing MCAccess native modules (1.12.x - 1.14.x

### ISSUE THREAD

**Issue by Lysandr0** [xaw3ep/NoCheatPlus#18]
### Full output of /ncp version
```
[INFO] ---- Version information ----
[INFO] #### Server ####
[INFO] git-Spigot-94af569-a3fdef8 ~MC: 1.14.4~
[INFO] detected: 1.14.4
[INFO] #### NoCheatPlus ####
[INFO] Plugin: 3.16.1-SNAPSHOT-b1153-CustomFork
[INFO] MCAccess: 1.13-1.14.4|? / Bukkit-API
[INFO] Features:
[INFO] blocks: BlocksMC1_4 | BlocksMC1_5 | BlocksMC1_6_1 | BlocksMC1_7_2 | BlocksMC1_8 | BlocksMC1_9 | BlocksMC1_10 | BlocksMC1_11 | BlocksMC1_12 | BlocksMC1_13 | BlocksMC1_14 | MCAccessBukkitModern
[INFO] checks: FastConsume | Gutenberg | HotFixFallingBlockPortalEnter | AttackFrequency | FlyingFrequency | KeepAliveFrequency
[INFO] defaults: pvpKnockBackVelocity
[INFO] packet-listeners: UseEntityAdapter | MovingFlying | OutgoingPosition | KeepAliveAdapter | SoundDistance | NoSlow
[INFO] Hooks: AllViolations~NCP~ 1.0
[INFO] #### Related Plugins ####
[INFO] ProtocolLib v4.5.0-SNAPSHOT
```
### Describe the issue
The feather falling effect doesn't apply to players, due to NCP not having a native module for 1.14 and running on Bukkit-API only. ([NCP Issue](https://github.com/NoCheatPlus/Issues/issues/17))

### Extra links/Videos (Including debug logs)
https://www.dropbox.com/s/r3rmd6e036zgvn0/Feather_fall.mov?dl=0

**Comment by MarkElf** [comment]
I was able to reproduce this and I added some framework for 1.12_r1 - 1.14_r1 (excluding 1.13_r2 as it was causing issues). I don't think they're compiling correctly though as the jars are just 2kbs with the pom.xml in them. The changes I made didn't resolve the issue in-game, it still set the MCAccess as "MCAccess: 1.13-1.14.4|? / Bukkit-API".
https://github.com/MarkElf/NoCheatPlus/commit/17f4e8f284bdca6450aa48fac919d1d386fed425
https://github.com/MarkElf/NoCheatPlus/commit/4c825ed5ad674389e09419699408de5c22a15c23

**Comment by Lysandr0** [comment]
I tried to copy all files (except the pom) from the 1.11 module, changing the version number and pasting them back in the CBDev one, needless to say, it didn't work :p NCP fails to compile with this maven goal `mvn -P nonfree_build -P all install`
Was thinking a bit too optimistically that this could be fixed so easily. :)

**Comment by MarkElf** [comment]
`mvn clean package install -P nonfree_build -P nonfree_include -P `all`
Is the current compile maven goal that we've been using. I think you pretty much tried what I did and I got it to compile minus 1.13_r2 though I don't think the modules were grabbing/downloading anything as they only contained the pom.xml in the jar.
Fix attempt here: https://github.com/xaw3ep/NoCheatPlus/commit/7053d0a0c791a11384164c86a29fc73af5f4d7f5

I think being in bukkit mode broke 'default' in the config for some sections like the enderpearl issue you brought you before. Not sure about performance but I assume there is going to a small hit there given performance is mentioned at all.

**Comment by Lysandr0** [comment]
I've quickly tested the fix attempt and it seems to be working fine.
Now for the BukkitAPI mode part, should I leave this ticket open or make a different one?

**Comment by xaw3ep** [comment]
Let me explain to you the differences between using BukkitAPI and CBreflect.
There will have some practical benefits when using CBreflect while BukkitAPI doesn't have. For instance:
- It defines most blocks for you. Which mean you most likely don't have to do it anymore, just some special blocks.
- It auto calculate the reducing damage when equipping armors. Not like the Bukkit, it only setdamage and sethealth without knowing damage source. So when you use NCP with BukkitAPI and died for being fallen from a high place, it just prints out "%player% died" not "%player% fell from a high place"
- Also there some more things like speed attribute, getWidth, getHeight of mobs/player for calculating fight direction, etc.

But I still don't know why asofold don't use it since 1.13. Maybe it unstable?
I added that commit just to help NCP to calculate falldamage for itself better. Not depending NMS.
